version: '3.8'

services:
  otif-diagnostic-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otif_diagnostic_tool
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    restart: always
